#!/bin/bash


USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/shell-roboshop"
SCRIPT_NAME=$( echo $0 | cut -d. -f1 )
SCRIPT_DIR=$PWD
MONGODB_HOST=mongodb.jrdaws.life
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

mkdir -p $LOGS_FOLDER
echo "script started executed at: $( "date" )" &>>$LOG_FILE
if [ $USERID -ne 0 ]
then
     echo "ERROR: please run this script with root privelage"
     exit 1
fi


VALIDATE(){
        if [ $1 -ne 0 ] 
    then
         echo -e "$2...$R FAILURE $N"
         exit 1
    else
         echo -e "$2....$G SUCCESS $N"
    fi     
}

dnf install mysql-server -y &>>$LOG_FILE
VALIDATE $? "installing mysql"
systemctl enable mysqld &>>$LOG_FILE
VALIDATE $? "enabling mysql"
systemctl start mysqld &>>$LOG_FILE
VALIDATE $? "starting mysql"  

mysql_secure_installation --set-root-pass RoboShop@1
VALIDATE $? "setting root pass"




END_TIME=$(date +%s)
TOTAL_TIME=$(( $END_TIME - $START_TIME ))
echo -e "script executed in: $Y $TOTAL_TIME seconds $N"